services:
  db:
    image: mariadb:10.11
    container_name: pod_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - pod_db_data:/var/lib/mysql

  api:
    build: .
    container_name: pod_api
    # Le port interne reste 8000 (c'est là que gunicorn/runserver écoute)
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      # MODIFICATION ICI : On utilise le port du .env pour l'extérieur
      - "${EXPOSITION_PORT}:8000"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS},0.0.0.0
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - CORS_ALLOW_ALL_ORIGINS=${CORS_ALLOW_ALL_ORIGINS:-False}

volumes:
  pod_db_data: